In [1]:
%load_ext autoreload
%autoreload 2

In [6]:
import ltcl
from ltcl.modules.components.linear import LULinear
import torch
from ltcl.modules.components.transforms import AffineMBDStep, AffineMBD

In [8]:
x = torch.rand(16, 40, 5)

In [9]:
af = AffineMBD(5,3)

In [13]:
af(x)[1]

tensor([-1.1027e-05, -1.1027e-05, -1.1027e-05, -1.1027e-05, -1.1027e-05,
        -1.1027e-05, -1.1027e-05, -1.1027e-05, -1.1027e-05, -1.1027e-05,
        -1.1027e-05, -1.1027e-05, -1.1027e-05, -1.1027e-05, -1.1027e-05,
        -1.1027e-05], grad_fn=<SumBackward1>)

In [155]:
af.forward(x[:,-1:], x[:,:-1])

(tensor([[ 0.3235,  0.9491,  0.0532,  0.6576,  0.4148],
         [ 0.7166,  0.1095,  0.7463,  0.3987,  0.9793],
         [ 0.3305,  0.2733,  0.8520,  0.6037,  0.2515],
         [ 0.4924,  0.8091,  0.8056,  0.4024,  0.7732],
         [ 0.6022,  0.8862,  0.7043,  0.1697,  0.6696],
         [ 0.0496,  0.1971,  0.6523,  0.4424,  0.8915],
         [-0.0115,  0.1774,  0.8889,  0.8541,  0.2516],
         [ 0.3977,  0.2453,  0.2623,  0.4421,  0.2898],
         [ 0.2855,  0.2246,  0.0081,  0.8036,  0.2670],
         [ 0.2552,  0.5046,  0.4937,  0.6082,  0.1018],
         [ 0.4508,  0.2224,  0.1069,  0.4133,  0.1139],
         [ 0.3427,  0.0823,  0.7638,  0.0330,  0.2589],
         [ 0.0620,  0.3701,  0.0370,  0.6001,  0.2942],
         [ 0.5898,  0.3147,  0.2667,  0.5897,  0.6487],
         [ 0.7326,  0.3662,  0.7883,  0.0882,  0.0971],
         [ 0.4932,  0.1823,  0.6074,  0.7244,  0.4798]], grad_fn=<AddBackward0>),
 tensor([-2.9802e-07, -2.9802e-07, -2.9802e-07, -2.9802e-07, -2.9802e-07,
    

In [130]:
import torch.nn as nn


In [159]:
ln = LULinear(5, identity_init=True, using_cache=True)

In [161]:
ln(x)

(tensor([[[0.6811, 0.2196, 0.6923, 0.0070, 0.1423],
          [0.3651, 0.8115, 0.6041, 0.6515, 0.1930],
          [0.4109, 0.1580, 0.2014, 0.5807, 0.5902],
          [0.7189, 0.1865, 0.3327, 0.3842, 0.4437]],
 
         [[0.2624, 0.8754, 0.7083, 0.1112, 0.1616],
          [0.8255, 0.9445, 0.4103, 0.4734, 0.3880],
          [0.2599, 0.5638, 0.8067, 0.4844, 0.7200],
          [0.0570, 0.6648, 0.8182, 0.3115, 0.1224]],
 
         [[0.5220, 0.6687, 0.3717, 0.3121, 0.3521],
          [0.8660, 0.4434, 0.6512, 0.5571, 0.3081],
          [0.3622, 0.2016, 0.5992, 0.3166, 0.5618],
          [0.9987, 0.2816, 0.7351, 0.0109, 0.2369]],
 
         [[0.9746, 0.6250, 0.5189, 0.8918, 0.1959],
          [0.1166, 0.8354, 0.4912, 0.6776, 0.6419],
          [0.9720, 0.6904, 0.8148, 0.4545, 0.2886],
          [0.0864, 0.3552, 0.7186, 0.3549, 0.0320]],
 
         [[0.6138, 0.9523, 0.2188, 0.4109, 0.8311],
          [0.5320, 0.9480, 0.9256, 0.7548, 0.1742],
          [0.6744, 0.2479, 0.4922, 0.8514, 0.0541],


In [86]:
x.new_ones(5)

tensor([1., 1., 1., 1., 1.])

In [68]:
y = x.unfold(dimension=1, size=3,step=1).swapaxes(-1, -2)

In [98]:
y.shape

torch.Size([16, 2, 3, 8])

In [109]:
y1 = y.reshape(-1, 8)

In [115]:
y1[0] + 0

tensor([0.4143, 0.9086, 0.2927, 0.6092, 0.5762, 0.6178, 0.6051, 0.1361])

In [122]:
import numpy as np
np.ones(12)[-12]

1.0

In [123]:
l = [1,2,3]

In [124]:
l[-3]

1

In [114]:
y[0,0,0]

tensor([0.4143, 0.9086, 0.2927, 0.6092, 0.5762, 0.6178, 0.6051, 0.1361])

In [110]:
y1.reshape(y.shape) == y

tensor([[[[True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True]],

         [[True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True]]],


        [[[True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True]],

         [[True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True]]],


        [[[True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True],
          [True, True, True, True, True, True, True, True]],

         [[True, True, True, True, True, True, True, True],
          [True, True, Tru

In [88]:
ln.forward_no_cache(x)[1]

torch.Size([])


tensor([-1.0830, -1.0830, -1.0830, -1.0830, -1.0830, -1.0830, -1.0830, -1.0830,
        -1.0830, -1.0830, -1.0830, -1.0830, -1.0830, -1.0830, -1.0830, -1.0830],
       grad_fn=<MulBackward0>)

In [94]:
a = 1 * torch.ones(12)/12

In [97]:
torch.stack(32 * [a]).shape

torch.Size([32, 12])

In [92]:
1 *  torch.ones(12) * torch.ones(12).T

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
y.shape

torch.Size([16, 2, 3, 8])

In [73]:
y[0, 0, :, :].shape

torch.Size([3, 8])

In [60]:
x[0]

tensor([[0.4143, 0.9086, 0.2927, 0.6092, 0.5762, 0.6178, 0.6051, 0.1361],
        [0.0492, 0.6251, 0.9643, 0.4910, 0.0401, 0.2222, 0.8633, 0.2307],
        [0.0836, 0.9884, 0.3025, 0.8867, 0.1311, 0.3248, 0.5133, 0.5176],
        [0.2459, 0.0536, 0.6596, 0.8216, 0.6418, 0.8858, 0.1912, 0.9826]])

In [49]:
y.shape

torch.Size([2, 3, 3])

In [45]:
x.shape

torch.Size([2, 5])

In [ ]:
5-3+1