In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import ltcl
from ltcl.modules.flow import TemporalMBDFlow
import torch

In [3]:
flow = TemporalMBDFlow(2, 4)

In [4]:
x = torch.rand(16, 8, 2)
y = torch.rand(16, 4, 2)

In [5]:
e, z, sum_log_abs_det_jacobians = flow(x, y)

In [6]:
e.shape, z.shape, sum_log_abs_det_jacobians.shape

(torch.Size([16, 8, 2]), torch.Size([16, 8, 2]), torch.Size([16]))

In [7]:
ee = flow.inverse(z, y)

In [15]:
xx

tensor([[[ 1.1024,  0.2298],
         [ 0.2473,  0.5270],
         [ 0.5614,  0.7286],
         [ 0.7730,  0.1539],
         [ 0.2617,  0.9627],
         [ 1.0517,  0.1954],
         [ 0.1676,  0.3306],
         [ 0.3420,  0.0963]],

        [[ 0.9097,  0.3173],
         [ 0.3686,  0.5901],
         [ 0.6449,  0.3130],
         [ 0.3734,  0.7964],
         [ 0.8818,  0.1728],
         [ 0.2298,  0.7219],
         [ 0.7429,  0.8687],
         [ 0.9072,  0.7282]],

        [[ 0.5666,  0.5609],
         [ 0.6025,  0.6774],
         [ 0.7241,  0.8919],
         [ 1.0019,  0.3394],
         [ 0.3764,  0.4686],
         [ 0.5129,  0.7041],
         [ 0.7381,  0.5735],
         [ 0.6643,  0.3979]],

        [[ 0.4535,  0.5770],
         [ 0.6428,  0.3193],
         [ 0.4015,  0.8231],
         [ 0.8921,  0.3096],
         [ 0.3408,  0.4082],
         [ 0.4695,  0.8523],
         [ 0.8801,  0.5278],
         [ 0.5988,  0.8954]],

        [[ 0.1791,  0.2866],
         [ 0.3414,  0.7522],
      

In [16]:
x

tensor([[[0.3726, 0.2033],
         [0.5605, 0.5166],
         [0.1789, 0.7360],
         [0.7317, 0.1680],
         [0.9265, 0.9011],
         [0.2598, 0.1669],
         [0.6394, 0.3294],
         [0.2916, 0.1033]],

        [[0.3626, 0.3147],
         [0.8271, 0.5831],
         [0.6186, 0.3182],
         [0.6094, 0.7855],
         [0.7094, 0.1705],
         [0.6957, 0.7011],
         [0.0496, 0.9102],
         [0.1354, 0.7816]],

        [[0.3752, 0.5641],
         [0.9400, 0.6644],
         [0.0711, 0.9405],
         [0.2931, 0.3329],
         [0.9029, 0.4658],
         [0.6035, 0.6906],
         [0.7948, 0.5857],
         [0.5012, 0.4203]],

        [[0.6318, 0.5776],
         [0.3366, 0.3432],
         [0.5033, 0.8182],
         [0.4310, 0.3096],
         [0.5145, 0.4141],
         [0.0703, 0.8639],
         [0.1025, 0.5632],
         [0.1275, 0.9217]],

        [[0.7562, 0.2873],
         [0.1816, 0.7553],
         [0.3507, 0.8110],
         [0.9993, 0.4157],
         [0.4792, 0.

In [10]:
sum_log_abs_det_jacobians

tensor([ -3.9754,   1.4525, -11.8307,   4.9286,  -7.9111,  -6.1972,   2.7244,
        -12.6433,  -8.9205,  -2.1613,  -2.2704,  -4.0597,   1.5329,  -0.9711,
         -3.9992,  -6.1606], grad_fn=<AddBackward0>)