In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import torch.nn as nn
from leap.modules.components.transition import LinearTransitionPrior, PNLTransitionPrior

In [2]:
trans = LinearTransitionPrior(2, 8)

In [4]:
trans = PNLTransitionPrior(2, 8)

In [8]:
x = torch.randn(64, 12, 8)

In [10]:
trans(x).shape

torch.Size([64, 12, 8])

In [104]:
(x[:,:,0] @ trans.weight[:,:,0].T) + (x[:,:,1] @ trans.weight[:,:,1].T)

tensor([[ 2.6759e-01, -6.9729e-01,  1.8165e-02,  4.9430e-01,  3.1976e-01,
         -7.6256e-01,  4.5451e-01, -9.6982e-01],
        [-4.1495e-01, -4.3766e-01,  9.5594e-01,  1.2355e+00,  7.6704e-01,
         -2.4684e-01,  1.4183e-01,  8.7121e-02],
        [-2.7177e-01,  1.4526e+00,  9.5389e-02, -4.5429e-01, -5.9495e-01,
          3.7063e-01, -8.8905e-01,  6.7668e-01],
        [ 2.1195e-02, -5.8942e-01,  6.0787e-01,  5.2836e-01,  7.3696e-01,
          4.6000e-01,  2.4584e-01, -1.0546e-01],
        [ 9.1101e-01, -1.9974e-01,  2.0299e-01,  3.8443e-01, -2.9113e-01,
         -1.7811e-01,  9.8967e-01,  7.2811e-01],
        [ 7.4127e-01, -6.5741e-01,  2.5843e-01,  2.4794e-01,  7.9740e-01,
         -5.1708e-01,  6.9951e-01, -6.1199e-01],
        [ 6.6758e-01,  8.1927e-01,  5.2549e-02,  5.9239e-01, -3.9636e-01,
         -3.8569e-01,  1.8624e-01,  5.3368e-01],
        [ 1.1693e+00,  4.9683e-02,  2.0195e-01, -1.2071e-01, -1.4591e-01,
          5.6300e-01,  1.6977e+00,  1.6874e-01],
        [-6.6493

In [108]:
trans.weight.T[0,:,:]

tensor([[ 1.3767e-01,  1.4692e-01,  9.0842e-02, -9.6999e-02, -9.0729e-03,
          1.3693e-01, -2.5660e-02, -7.3164e-02],
        [ 3.3346e-02,  2.0094e-01, -3.2634e-05, -2.0764e-01, -1.3725e-01,
          1.2943e-01,  1.0467e-01,  1.6331e-01],
        [-2.0828e-01,  4.9805e-02, -1.6471e-01, -2.1212e-01,  9.2654e-02,
          2.9406e-02,  4.7247e-02, -2.0034e-01],
        [-1.3460e-01, -1.0172e-01,  5.6871e-02,  1.5931e-03,  1.3557e-01,
         -8.0023e-02, -2.0404e-01, -1.6861e-01],
        [-2.0532e-01,  8.4937e-02, -1.9395e-01, -1.6879e-01, -2.0289e-01,
          1.3826e-01, -2.3561e-02,  1.0333e-01],
        [-1.5216e-01,  2.4220e-01, -2.4783e-01, -3.2245e-02, -1.6978e-01,
         -2.0096e-01, -2.4322e-01, -1.0162e-03],
        [ 5.1656e-02, -8.0893e-02,  7.4708e-02,  1.7272e-01,  1.2101e-01,
          1.0929e-01,  2.4145e-01, -8.7062e-04],
        [ 1.3389e-01, -1.6453e-01, -1.9605e-01, -1.1953e-02,  9.9565e-02,
         -1.5700e-01,  1.9424e-01, -1.5122e-01]], grad_fn=<SliceB

In [109]:
trans.weight[:,:,0].T

tensor([[ 1.3767e-01,  1.4692e-01,  9.0842e-02, -9.6999e-02, -9.0729e-03,
          1.3693e-01, -2.5660e-02, -7.3164e-02],
        [ 3.3346e-02,  2.0094e-01, -3.2634e-05, -2.0764e-01, -1.3725e-01,
          1.2943e-01,  1.0467e-01,  1.6331e-01],
        [-2.0828e-01,  4.9805e-02, -1.6471e-01, -2.1212e-01,  9.2654e-02,
          2.9406e-02,  4.7247e-02, -2.0034e-01],
        [-1.3460e-01, -1.0172e-01,  5.6871e-02,  1.5931e-03,  1.3557e-01,
         -8.0023e-02, -2.0404e-01, -1.6861e-01],
        [-2.0532e-01,  8.4937e-02, -1.9395e-01, -1.6879e-01, -2.0289e-01,
          1.3826e-01, -2.3561e-02,  1.0333e-01],
        [-1.5216e-01,  2.4220e-01, -2.4783e-01, -3.2245e-02, -1.6978e-01,
         -2.0096e-01, -2.4322e-01, -1.0162e-03],
        [ 5.1656e-02, -8.0893e-02,  7.4708e-02,  1.7272e-01,  1.2101e-01,
          1.0929e-01,  2.4145e-01, -8.7062e-04],
        [ 1.3389e-01, -1.6453e-01, -1.9605e-01, -1.1953e-02,  9.9565e-02,
         -1.5700e-01,  1.9424e-01, -1.5122e-01]], grad_fn=<Permut

In [105]:
trans(x)[:,:,0]

tensor([[ 2.6759e-01, -6.9729e-01,  1.8165e-02,  4.9430e-01,  3.1976e-01,
         -7.6256e-01,  4.5451e-01, -9.6982e-01],
        [-4.1495e-01, -4.3766e-01,  9.5594e-01,  1.2355e+00,  7.6704e-01,
         -2.4684e-01,  1.4183e-01,  8.7122e-02],
        [-2.7177e-01,  1.4526e+00,  9.5389e-02, -4.5429e-01, -5.9495e-01,
          3.7063e-01, -8.8905e-01,  6.7668e-01],
        [ 2.1195e-02, -5.8942e-01,  6.0787e-01,  5.2836e-01,  7.3696e-01,
          4.6000e-01,  2.4584e-01, -1.0546e-01],
        [ 9.1101e-01, -1.9974e-01,  2.0299e-01,  3.8443e-01, -2.9113e-01,
         -1.7811e-01,  9.8967e-01,  7.2811e-01],
        [ 7.4127e-01, -6.5741e-01,  2.5843e-01,  2.4794e-01,  7.9740e-01,
         -5.1708e-01,  6.9951e-01, -6.1199e-01],
        [ 6.6758e-01,  8.1927e-01,  5.2549e-02,  5.9239e-01, -3.9636e-01,
         -3.8569e-01,  1.8624e-01,  5.3368e-01],
        [ 1.1693e+00,  4.9683e-02,  2.0195e-01, -1.2071e-01, -1.4591e-01,
          5.6300e-01,  1.6977e+00,  1.6874e-01],
        [-6.6493

In [58]:
(x[:,:,0] @ trans.weight[:,:,0] + x[:,:,1] @ trans.weight[:,:,1])

tensor([[-7.8677e-01, -1.2127e+00,  6.5318e-02,  1.0874e+00,  5.3775e-02,
          5.0511e-01,  6.7316e-01,  6.7484e-01],
        [ 9.4544e-01,  8.1682e-01,  5.8433e-01, -4.3046e-01,  4.0859e-01,
          4.5026e-01,  3.2894e-01,  5.8249e-01],
        [-6.1833e-01,  8.3107e-01,  4.7433e-01, -2.0487e-01,  2.7271e-01,
          4.5171e-01, -1.5661e-01, -5.1651e-01],
        [ 1.6650e+00,  5.4054e-01, -3.5590e-01, -1.4055e+00, -1.9859e-01,
         -1.5287e-01, -1.1094e+00,  3.4642e-01],
        [-2.8306e-01,  1.0285e+00,  1.7478e-01,  5.7278e-01,  5.3371e-02,
          6.0996e-02,  1.1061e-01, -6.0918e-01],
        [ 5.2371e-01,  2.5782e-01, -7.3359e-01,  4.6657e-01, -1.2850e-01,
         -4.7410e-01,  1.7165e-01, -2.4554e-01],
        [ 4.5918e-01, -4.0167e-01, -2.8298e-01, -1.7732e-01,  3.8862e-01,
         -2.2099e-01,  2.7365e-01, -2.7303e-01],
        [ 3.8375e-01, -1.6185e-01,  2.1374e-01,  6.1261e-01,  1.6149e-01,
          1.1930e+00, -1.0521e-01,  4.6104e-01],
        [ 5.8165

In [70]:
trans(x)[:,]

torch.Size([64, 8, 12])

In [77]:
trans.weight.shape

torch.Size([8, 8, 1])